name: "Pull Request"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            feature
            fix
            JIRA-\d+
          scopes: |
            modules
            inputs
            ci
            JIRA-\d+
          requireScope: true
          disallowScopes: |
            release
            [A-Z]+
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          headerPatternCorrespondence: type, scope, subject
