name: "YAML & JSON"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  json-yaml-validate:
    name: Validate files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.3.2
        with:
          comment: "true"
